# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

partial1CopulaCPP <- function(u, v, h, copfun) {
    .Call('qte_partial1CopulaCPP', PACKAGE = 'qte', u, v, h, copfun)
}

getListParitalQuantCPP <- function(u, v, h, copfun) {
    .Call('qte_getListParitalQuantCPP', PACKAGE = 'qte', u, v, h, copfun)
}

getJointCPP <- function(x, y) {
    .Call('qte_getJointCPP', PACKAGE = 'qte', x, y)
}

getJointUVCPP <- function(u, v, x1, y1) {
    .Call('qte_getJointUVCPP', PACKAGE = 'qte', u, v, x1, y1)
}

quantileCPP <- function(x, probs) {
    .Call('qte_quantileCPP', PACKAGE = 'qte', x, probs)
}

getListQuantilesCPP <- function(partialvals, t) {
    .Call('qte_getListQuantilesCPP', PACKAGE = 'qte', partialvals, t)
}

testy <- function() {
    .Call('qte_testy', PACKAGE = 'qte')
}

meanC <- function(x) {
    .Call('qte_meanC', PACKAGE = 'qte', x)
}

rcpp_hello_world <- function() {
    .Call('qte_rcpp_hello_world', PACKAGE = 'qte')
}

