---
title: "panel.qtet"
author: "Brantly Callaway"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{panel.qtet}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# Estimating Quantile Treatment Effects using Callaway and Li (2016)

123456

We consider the case with exactly 3 periods of panel data: period 0, 1, and 2.  In period 0 and 1, no one is treated.  In period 2, some individuals are treated.  Whether or not an individual is treated depends on some covariates $X$.

In this example, we consider the following data generating process:

$$  Y_{it}(d) = \mu(d) + \theta_t \times x + v_i + \epsilon_{it} $$

where $\theta_t$ is a time period fixed effect, $v_i$ is an individual-specific fixed effect and $\epsilon_{it}$ is a noise term.  The QTT is constant across quantiles and given by $TE = \mu(1) - \mu(0)$.  $X$ is a binary covariate that is 0 for 1/3 of the population and 1 for everyone else.  Individuals with $X=1$ have a time trend given by $\theta_t$; there is no trend in outcomes for individuals with $X=1$.  The individual-specific fixed effects, we assume are distributed $N(d, d+1)$ and $\epsilon_{it} \sim N(0,1)$ and is iid.  Finally, we assume that $P(D=1|X=0)=2/3$ and $P(D=1|X=1) = 1/3$.

```{r}
## Generate the data

n <- 100 ## sample size
te <- 1 ## treatment effect constant across quantiles
thet2 <- 2 ## time effect in period 2
thet1 <- 1 ## time effect in period 1 
x <- sample(c(0,1), n, replace=T, prob=c(1/3,2/3)) ## a covariate

```